services:
    database:
        image: postgres:16
        container_name: taw_database
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped

    backend:
        build:
            context: ./backend
            target: development # cambia in production
        container_name: taw_backend
        environment:
            - PORT=3000
            - DB_HOST=database
            - DB_PORT=5432
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_NAME=mydatabase
            - JWT_SECRET=cambia-questo-segreto-in-produzione
            - JWT_EXPIRES_IN=7d
            - SEED=true # seeding  all'avvio
        ports:
            - '3000:3000'
        volumes: # CANCELLA IN PROD
            - ./:/workspace # specchia tutta la root del progetto
            - ./backend:/app # collega /backend (la cartella del progetto) a /app (la cartella dentro il container creata da WORKDIR /app nel Dockerfile)
            - /app/node_modules # ma node_modules rimane isolato
        depends_on:
            - database
        restart: unless-stopped

    # frontend:
    #     build:
    #         context: ./frontend
    #         target: development
    #     container_name: taw_frontend
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./frontend:/app             # Specchia il codice Angular
    #         - /app/node_modules           # Isola i pacchetti Linux
    #     depends_on:
    #         - backend
    #     restart: unless-stopped

volumes:
    pgdata:
